version: 2.1
orbs:
  slack: circleci/slack@3.4.2

jobs:
  lint_and_test:
    docker:
      - image: cimg/node:12.4.0
    steps:
      - checkout
      - run:
          name: Install
          command: npm install
      - run:
          name: Lint
          command: npm run lint
      - run:
          name: Test
          command: npm run test
      - slack/status:
          fail_only: true
          only_for_branches: master
          failure_message: ":facepalm:  Failed job $CIRCLE_JOB  :homer-disappear:"


workflows:
  commit-workflow:
    jobs:
      - lint_and_test
